name: keep_keyboard_popup_menu
description: A popup menu that will keep keyboard open.
version: 2.0.6
repository: https://github.com/PegasisForever/keep_keyboard_popup_menu

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0


flutter:
